### ISSUE TITLE
Getting DivisionByZero errors logged

### ISSUE THREAD

**Issue by ruifung** [travisghansen/hass-opnsense#142]
My OPNsense instance seems to show a lot of DivisionByZero PHP errors logged.
OPNsense: 24.1.10_2-amd64
Integration: v0.1.21

Example below:
```
[13-Jul-2024 18:04:53 Asia/Kuala_Lumpur] PHP Fatal error:  Uncaught DivisionByZeroError: Division by zero in /usr/local/etc/inc/xmlrpc/hass.inc(12) : eval()'d code:96
Stack trace:
#0 /usr/local/etc/inc/xmlrpc/hass.inc(12): eval()
#1 /usr/local/opnsense/contrib/IXR/IXR_Library.php(446): exec_php_xmlrpc('\nini_set('displ...')
#2 /usr/local/opnsense/contrib/IXR/IXR_Library.php(384): IXR_Server->call('opnsense.exec_p...', '\nini_set('displ...')
#3 /usr/local/opnsense/contrib/IXR/IXR_Library.php(357): IXR_Server->serve('<?xml version='...')
#4 /usr/local/etc/inc/xmlrpc.inc(67): IXR_Server->__construct(Array)
#5 /usr/local/www/xmlrpc.php(104): XMLRPCServer->start()
#6 {main}
  thrown in /usr/local/etc/inc/xmlrpc/hass.inc(12) : eval()'d code on line 96
```

also other errors logged, just in case:
```
[15-Jul-2024 03:03:56 Asia/Kuala_Lumpur] PHP Fatal error:  Uncaught TypeError: Unsupported operand types: string / int in /usr/local/etc/inc/system.inc:851
Stack trace:
#0 /usr/local/etc/inc/filter.inc(747): get_memory()
#1 /usr/local/www/widgets/api/plugins/system.inc(94): default_state_size()
#2 /usr/local/www/widgets/api/plugins/system.inc(217): system_api_kernel()
#3 /usr/local/etc/inc/xmlrpc/hass.inc(12) : eval()'d code(69): system_api()
#4 /usr/local/etc/inc/xmlrpc/hass.inc(12): eval()
#5 /usr/local/opnsense/contrib/IXR/IXR_Library.php(446): exec_php_xmlrpc('\nini_set('displ...')
#6 /usr/local/opnsense/contrib/IXR/IXR_Library.php(384): IXR_Server->call('opnsense.exec_p...', '\nini_set('displ...')
#7 /usr/local/opnsense/contrib/IXR/IXR_Library.php(357): IXR_Server->serve('<?xml version='...')
#8 /usr/local/etc/inc/xmlrpc.inc(67): IXR_Server->__construct(Array)
#9 /usr/local/www/xmlrpc.php(104): XMLRPCServer->start()
#10 {main}
  thrown in /usr/local/etc/inc/system.inc on line 851
```
and
```
[14-Jul-2024 17:27:40 Asia/Kuala_Lumpur] PHP Fatal error:  Uncaught ValueError: array_combine(): Argument #1 ($keys) and argument #2 ($values) must have the same number of elements in /usr/local/www/widgets/api/plugins/system.inc:34
Stack trace:
#0 /usr/local/www/widgets/api/plugins/system.inc(34): array_combine(Array, Array)
#1 /usr/local/www/widgets/api/plugins/system.inc(211): system_api_cpu_stats()
#2 /usr/local/etc/inc/xmlrpc/hass.inc(12) : eval()'d code(69): system_api()
#3 /usr/local/etc/inc/xmlrpc/hass.inc(12): eval()
#4 /usr/local/opnsense/contrib/IXR/IXR_Library.php(446): exec_php_xmlrpc('\nini_set('displ...')
#5 /usr/local/opnsense/contrib/IXR/IXR_Library.php(384): IXR_Server->call('opnsense.exec_p...', '\nini_set('displ...')
#6 /usr/local/opnsense/contrib/IXR/IXR_Library.php(357): IXR_Server->serve('<?xml version='...')
#7 /usr/local/etc/inc/xmlrpc.inc(67): IXR_Server->__construct(Array)
#8 /usr/local/www/xmlrpc.php(104): XMLRPCServer->start()
#9 {main}
  thrown in /usr/local/www/widgets/api/plugins/system.inc on line 34
```

**Comment by alexdelprete** [comment]
please test v0.2.0 and in case create another issue.
