### ISSUE TITLE
"Invalid Uptime format" on 0.2.0-beta.2

### ISSUE THREAD

**Issue by tophattwaffle** [travisghansen/hass-opnsense#158]
OPNsense 24.1.10_8-amd64
Home Assistant 2024.9.1

Recently upgraded Home Assistant and OPNSense didn't come back up. Tried all the pre-release versions without success.

Get the following with debug logging enabled.
```
This error originated from a custom integration.

Logger: custom_components.opnsense
Source: helpers/update_coordinator.py:354
integration: OPNsense (documentation, issues)
First occurred: 17:17:55 (7 occurrences)
Last logged: 17:19:59

Unexpected error fetching Overlord OPNsense state data
Unexpected error fetching Overseer OPNsense state data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 354, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 271, in _async_update_data
    return await self.update_method()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/opnsense/__init__.py", line 98, in async_update_data
    await hass.async_add_executor_job(lambda: data.update())
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/opnsense/__init__.py", line 98, in <lambda>
    await hass.async_add_executor_job(lambda: data.update())
                                              ^^^^^^^^^^^^^
  File "/config/custom_components/opnsense/__init__.py", line 317, in update
    self._state["telemetry"] = self._get_telemetry()
                               ^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/opnsense/__init__.py", line 226, in inner
    response = func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/opnsense/__init__.py", line 250, in _get_telemetry
    return self._client.get_telemetry()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/opnsense/pyopnsense/__init__.py", line 104, in inner
    raise err
  File "/config/custom_components/opnsense/pyopnsense/__init__.py", line 101, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/opnsense/pyopnsense/__init__.py", line 926, in get_telemetry
    telemetry["system"] = self._get_telemetry_system()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/opnsense/pyopnsense/__init__.py", line 104, in inner
    raise err
  File "/config/custom_components/opnsense/pyopnsense/__init__.py", line 101, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/opnsense/pyopnsense/__init__.py", line 1132, in _get_telemetry_system
    raise ValueError("Invalid uptime format")
ValueError: Invalid uptime format
```

**Comment by tophattwaffle** [comment]
Updated to OPNSense 24.7.1 and all seems good now.
