### ISSUE TITLE
Integration stopped working after 0.2.0 update

### ISSUE THREAD

**Issue by jesmak** [travisghansen/hass-opnsense#176]
After updating to 0.2.0, integration no longer started. It kept retrying without success. This is what was in the logs:

```
2024-09-09 20:55:29.843 ERROR (MainThread) [custom_components.opnsense] Unexpected error fetching HUNSN RJ34 OPNsense state data
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 354, in _async_refresh
self.data = await self._async_update_data()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 271, in _async_update_data
return await self.update_method()
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/opnsense/__init__.py", line 98, in async_update_data
await hass.async_add_executor_job(lambda: data.update())
File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/opnsense/__init__.py", line 98, in <lambda>
await hass.async_add_executor_job(lambda: data.update())
^^^^^^^^^^^^^
File "/config/custom_components/opnsense/__init__.py", line 317, in update
self._state["telemetry"] = self._get_telemetry()
^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/opnsense/__init__.py", line 226, in inner
response = func(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/opnsense/__init__.py", line 250, in _get_telemetry
return self._client.get_telemetry()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/opnsense/pyopnsense/__init__.py", line 104, in inner
raise err
File "/config/custom_components/opnsense/pyopnsense/__init__.py", line 101, in inner
return func(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/opnsense/pyopnsense/__init__.py", line 926, in get_telemetry
telemetry["system"] = self._get_telemetry_system()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/opnsense/pyopnsense/__init__.py", line 104, in inner
raise err
File "/config/custom_components/opnsense/pyopnsense/__init__.py", line 101, in inner
return func(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/opnsense/pyopnsense/__init__.py", line 1132, in _get_telemetry_system
raise ValueError("Invalid uptime format")
ValueError: Invalid uptime format
```

Removed the whole entry and tried to add it again, but adding the device fails with another error after entering the URL, key, secret, firewall name and trying to go forward:

```
2024-09-09 22:11:35.900 ERROR (SyncWorker_36) [custom_components.opnsense.pyopnsense] Invalid data returned from exec_php for get_system_info. TypeError: string indices must be integers, not 'str'. Ensure the OPNsense user connected to HA either has full Admin access or specifically has the 'XMLRPC Library' privilege.
2024-09-09 22:11:36.001 ERROR (MainThread) [custom_components.opnsense.config_flow] Unexpected err=KeyError('device_id'), type(err)=<class 'KeyError'>
```

**Comment by Snuffy2** [comment]
What OPNsense firmware are you running? If it is <24.7, please try the pre-release v0.2.1-beta.1 or wait until the next release.
[How to enable pre-release versions for an integration in HACS](https://hacs.xyz/docs/use/entities/switch/)

**Comment by jesmak** [comment]
I was originally using an older version, but updated to 24.7.3_1 which did not fix the issue. After your comment though I looked a bit more into this. Tested the beta version etc. Finally found two separate issues. The Home Assistant plugin in OPNsense showed a notification that it has an invalid configuration, so I reinstalled it which got rid of the error. The integration still didn't work though so after investigating a bit more, I noticed that the API key I was using, was for a user that did not have admin rights. I don't know if admin rights is a new requirement, or if it has been there before but OPNsense screwed something up during the update. In any case, adding admin privileges in OPNsense for the user finally fixed the problem. Closing this issue as it ended up being a user error.

**Comment by jesmak** [comment]
I was originally using an older version, but updated to 24.7.3_1 which did not fix the issue. After your comment though I looked a bit more into this. Tested the beta version etc. Finally found two separate issues. The Home Assistant plugin in OPNsense showed a notification that it has an invalid configuration, so I reinstalled it which got rid of the error. The integration still didn't work though so after investigating a bit more, I noticed that the API key I was using, was for a user that did not have admin rights. I don't know if admin rights is a new requirement, or if it has been there before but OPNsense screwed something up during the update. In any case, adding admin privileges in OPNsense for the user finally fixed the problem. Closing this issue as it ended up being a user error.

**Comment by alexdelprete** [comment]
> I don't know if admin rights is a new requirement

Since v0.2.0 we recommend admin privileged account, but we also documented (but not recommended) granular privileges. You can find details [here](https://github.com/travisghansen/hass-opnsense#opnsense).
