### ISSUE TITLE
v0.3.0-beta.2 issues: integration won't load

### ISSUE THREAD

**Issue by alexdelprete** [travisghansen/hass-opnsense#199]
Hi @Snuffy2, just upgraded to beta.2 from beta.1 (that worked), and have some issues that stops integration from starting:

```python
Logger: custom_components.opnsense.pyopnsense
Source: custom_components/opnsense/pyopnsense/__init__.py:143
integration: OPNsense
First occurred: 02:14:35 (1 occurrences)
Last logged: 02:14:35

Invalid data returned from get_config_section
```

```python
Logger: custom_components.opnsense.pyopnsense
Source: custom_components/opnsense/pyopnsense/__init__.py:98
integration: OPNsense (documentation, issues)
First occurred: 02:14:33 (9 occurrences)
Last logged: 02:14:35

Error in get_services. AttributeError: 'NoneType' object has no attribute 'keys'
Error in get_carp_interfaces. RuntimeError: Caught blocking call to putrequest with args (<http.client.HTTPConnection object at 0x75b9b4c07500>, 'POST', '/xmlrpc.php') inside the event loop by custom integration 'opnsense' at custom_components/opnsense/pyopnsense/__init__.py, line 123: methods = proxy.system.listMethods(). (offender: /usr/local/lib/python3.12/xmlrpc/client.py, line 1284: connection.putrequest("POST", handler, skip_accept_encoding=True)), please create a bug report at https://github.com/travisghansen/hass-opnsense/issues For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#putrequest
Error in get_carp_status. RuntimeError: Caught blocking call to putrequest with args (<http.client.HTTPConnection object at 0x75b99728bf20>, 'POST', '/xmlrpc.php') inside the event loop by custom integration 'opnsense' at custom_components/opnsense/pyopnsense/__init__.py, line 123: methods = proxy.system.listMethods(). (offender: /usr/local/lib/python3.12/xmlrpc/client.py, line 1284: connection.putrequest("POST", handler, skip_accept_encoding=True)), please create a bug report at https://github.com/travisghansen/hass-opnsense/issues For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#putrequest
Error in are_notices_pending. RuntimeError: Caught blocking call to putrequest with args (<http.client.HTTPConnection object at 0x75b99754a150>, 'POST', '/xmlrpc.php') inside the event loop by custom integration 'opnsense' at custom_components/opnsense/pyopnsense/__init__.py, line 123: methods = proxy.system.listMethods(). (offender: /usr/local/lib/python3.12/xmlrpc/client.py, line 1284: connection.putrequest("POST", handler, skip_accept_encoding=True)), please create a bug report at https://github.com/travisghansen/hass-opnsense/issues For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#putrequest
Error in get_notices. RuntimeError: Caught blocking call to putrequest with args (<http.client.HTTPConnection object at 0x75b9a0875820>, 'POST', '/xmlrpc.php') inside the event loop by custom integration 'opnsense' at custom_components/opnsense/pyopnsense/__init__.py, line 123: methods = proxy.system.listMethods(). (offender: /usr/local/lib/python3.12/xmlrpc/client.py, line 1284: connection.putrequest("POST", handler, skip_accept_encoding=True)), please create a bug report at https://github.com/travisghansen/hass-opnsense/issues For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#putrequest
```

```python
Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:361
integration: Sensor (documentation, issues)
First occurred: 02:14:35 (1 occurrences)
Last logged: 02:14:35

Error while setting up opnsense platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 361, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/opnsense/sensor.py", line 361, in async_setup_entry
    cem.process_entities()
  File "/config/custom_components/opnsense/__init__.py", line 224, in process_entities
    entities = self.process_entities_callback(self.hass, self.config_entry)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/opnsense/sensor.py", line 111, in process_entities_callback
    for interface in state["carp_interfaces"]:
TypeError: 'NoneType' object is not iterable
```

```python
Logger: homeassistant.components.switch
Source: helpers/entity_platform.py:361
integration: Switch (documentation, issues)
First occurred: 02:14:35 (1 occurrences)
Last logged: 02:14:35

Error while setting up opnsense platform for switch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 361, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/opnsense/switch.py", line 198, in async_setup_entry
    cem.process_entities()
  File "/config/custom_components/opnsense/__init__.py", line 224, in process_entities
    entities = self.process_entities_callback(self.hass, self.config_entry)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/opnsense/switch.py", line 40, in process_entities_callback
    if "filter" in state["config"].keys():
                   ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'keys'
```

**Comment by Snuffy2** [comment]
Yeah, same for me. Trying to sort out what happened now.

**Comment by Snuffy2** [comment]
Give v0.3.0-beta.3 a try. 

PR #190 was the issue. I wrote and tested it but I tested it before I moved everything to async. It will need to be reworked.

**Comment by alexdelprete** [comment]
Works! Thanks.
