### ISSUE TITLE
[Bug]: Migration error after upgrading to v0.3.5

### ISSUE THREAD

**Issue by rama31244** [travisghansen/hass-opnsense#259]
### What happened?

Hi, I recently upgraded to v0.3.5 and my presence detection stopped working. When I checked the log, I saw there was a migration error as outlined below. I've also included the full debug log too 

### hass-opnsense Version

0.3.5

### OPNsense Firmware

OPNsense 24.7.6-amd64

### Home Assistant Version

2024.10.2

### Relevant logs

```shell
Error migrating entry OPNsense for opnsense
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/configentries.py", line 933, in asyncmigrate
    result = await component.async_migrate_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/opnsense/__init.py", line 315, in async_migrate_entry
    new_dev = device_registry.async_update_device(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/device_registry.py", line 1027, in async_update_device
    new_values["identifiers"] = self._validate_identifiers(
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/device_registry.py", line 1133, in _validate_identifiers
    raise DeviceIdentifierCollisionError(identifiers, existing_device)
homeassistant.helpers.device_registry.DeviceIdentifierCollisionError: Identifiers {('opnsense', 'MAC ADDRESS')} already registered with DeviceEntry(area_id=None, config_entries={'**'}, configuration_url='https://192.168.1.1/', connections=set(), created_at=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=datetime.timezone.utc), disabled_by=None, entry_type=None, hw_version=None, id='&**', identifiers={('opnsense', MAC ADDRESS labels=set(), manufacturer='Deciso B.V.', model='OPNsense', model_id=None, modified_at=datetime.datetime(2024, 10, 11, 20, 0, 43, 592699, tzinfo=datetime.timezone.utc), name_by_user=None, name='OPNsense', primary_config_entry='**', serial_number=None, suggested_area=None, sw_version='24.7.5_3', via_device_id=None, is_new=False)
```

### Additional Details

[home-assistant_opnsense_2024-10-13T00-25-11.841Z.log](https://github.com/user-attachments/files/17352571/home-assistant_opnsense_2024-10-13T00-25-11.841Z.log)

**Comment by Snuffy2** [comment]
Interesting, did you have a duplicate OPNsense entry before this by chance?

**Comment by rama31244** [comment]
Maybe but I'm not sure why though
![Uploading Screenshot 2024-10-13 at 2.57.22 pm.png…]()
. When I click on the integration, there are 5 entries (see attached screenshot). Should there just be one?

**Comment by rama31244** [comment]
Yeh, I'm an idiot. Once I deleted all 5 and reinstalled, everything works fine
