### ISSUE TITLE
OpnSense Ver 23.1.4_1: /usr/local/etc/inc/xmlrpc/hass.inc(12) : eval()'d code:37

### ISSUE THREAD

**Issue by cnu80** [travisghansen/hass-opnsense#71]
Hi, after opnsense update, the connection is broken between HASS and OpnSense.

Following error,  I get from opnsense:

```
[22-Mar-2023 07:32:28 Europe/Vienna] PHP Fatal error:  Uncaught Error: Call to undefined function openvpn_get_active_servers() in /usr/local/etc/inc/xmlrpc/hass.inc(12) : eval()'d code:37
Stack trace:
#0 /usr/local/etc/inc/xmlrpc/hass.inc(12): eval()
#1 /usr/local/opnsense/contrib/IXR/IXR_Library.php(446): exec_php_xmlrpc('\nini_set('displ...')
#2 /usr/local/opnsense/contrib/IXR/IXR_Library.php(384): IXR_Server->call('opnsense.exec_p...', '\nini_set('displ...')
#3 /usr/local/opnsense/contrib/IXR/IXR_Library.php(357): IXR_Server->serve('__construct(Array)
#5 /usr/local/www/xmlrpc.php(104): XMLRPCServer->start()
#6 {main}
  thrown in /usr/local/etc/inc/xmlrpc/hass.inc(12) : eval()'d code on line 37
[22-Mar-2023 07:32:52 Europe/Vienna] PHP Fatal error:  Uncaught Error: Call to undefined function openvpn_get_active_servers() in /usr/local/etc/inc/xmlrpc/hass.inc(12) : eval()'d code:37
Stack trace:
#0 /usr/local/etc/inc/xmlrpc/hass.inc(12): eval()
#1 /usr/local/opnsense/contrib/IXR/IXR_Library.php(446): exec_php_xmlrpc('\nini_set('displ...')
#2 /usr/local/opnsense/contrib/IXR/IXR_Library.php(384): IXR_Server->call('opnsense.exec_p...', '\nini_set('displ...')
#3 /usr/local/opnsense/contrib/IXR/IXR_Library.php(357): IXR_Server->serve('__construct(Array)
#5 /usr/local/www/xmlrpc.php(104): XMLRPCServer->start()
#6 {main}
  thrown in /usr/local/etc/inc/xmlrpc/hass.inc(12) : eval()'d code on line 37
```

**Comment by alexdelprete** [comment]
Are you using latest version of the component released yesterday?

**Comment by cnu80** [comment]
Hi, thanks for the hint. There was a problem with HACS, the new version was not shown. With version (v0.1.15), the error is gone. THANKS

**Comment by alexdelprete** [comment]
No problem, only one advice as a general rule: before opening an issue, search past issues, maybe you'll find that someone else already raised it. :)

Can you please close the issue now? Thanks.
