### ISSUE TITLE
23.7 breaks integration: openvpn_config() removed

### ISSUE THREAD

**Issue by alexdelprete** [travisghansen/hass-opnsense#92]
OPNsense 23.7 broke the integration; function `openvpn_config()` is missing, probably removed like it happened recently for `openvpn_get_active_servers()` (PR #90)

```
#4 /usr/local/opnsense/contrib/IXR/IXR_Library.php(357): IXR_Server->serve('<?xml version='...')
#5 /usr/local/etc/inc/xmlrpc.inc(67): IXR_Server->__construct(Array)
#6 /usr/local/www/xmlrpc.php(104): XMLRPCServer->start()
#7 {main}
  thrown in /usr/local/etc/inc/xmlrpc/hass.inc(12) : eval()'d code on line 46
[03-Aug-2023 12:22:14 Europe/Rome] PHP Fatal error:  Uncaught Error: Call to undefined function openvpn_config() in /usr/local/etc/inc/xmlrpc/hass.inc(12) : eval()'d code:46
Stack trace:
#0 /usr/local/etc/inc/xmlrpc/hass.inc(12) : eval()'d code(60): openvpn_get_active_servers()
#1 /usr/local/etc/inc/xmlrpc/hass.inc(12): eval()
#2 /usr/local/opnsense/contrib/IXR/IXR_Library.php(446): exec_php_xmlrpc('\nini_set('displ...')
#3 /usr/local/opnsense/contrib/IXR/IXR_Library.php(384): IXR_Server->call('opnsense.exec_p...', '\nini_set('displ...')
#4 /usr/local/opnsense/contrib/IXR/IXR_Library.php(357): IXR_Server->serve('<?xml version='...')
#5 /usr/local/etc/inc/xmlrpc.inc(67): IXR_Server->__construct(Array)
#6 /usr/local/www/xmlrpc.php(104): XMLRPCServer->start()
#7 {main}
  thrown in /usr/local/etc/inc/xmlrpc/hass.inc(12) : eval()'d code on line 46
[03-Aug-2023 12:22:44 Europe/Rome] PHP Fatal error:  Uncaught Error: Call to undefined function openvpn_config() in /usr/local/etc/inc/xmlrpc/hass.inc(12) : eval()'d code:46
Stack trace:
#0 /usr/local/etc/inc/xmlrpc/hass.inc(12) : eval()'d code(60): openvpn_get_active_servers()
#1 /usr/local/etc/inc/xmlrpc/hass.inc(12): eval()
#2 /usr/local/opnsense/contrib/IXR/IXR_Library.php(446): exec_php_xmlrpc('\nini_set('displ...')
#3 /usr/local/opnsense/contrib/IXR/IXR_Library.php(384): IXR_Server->call('opnsense.exec_p...', '\nini_set('displ...')
#4 /usr/local/opnsense/contrib/IXR/IXR_Library.php(357): IXR_Server->serve('<?xml version='...')
#5 /usr/local/etc/inc/xmlrpc.inc(67): IXR_Server->__construct(Array)
#6 /usr/local/www/xmlrpc.php(104): XMLRPCServer->start()
#7 {main}
```

**Comment by Axsgranted** [comment]
I'm on OPNsense 23.7, using openvpn and using the integration but I don'th ave this issue

**Comment by alexdelprete** [comment]
> I'm on OPNsense 23.7, using openvpn and using the integration but I don'th ave this issue

Sorry for the late reply. You were right, I redownloaded the component from HACS and restarted, everything's working fine. I'm on OPNsense 23.7.2 and HA 2023.9.0 now.

In the past I manually patched some files while testing things, and probably I forgot to remove them.
